name: Semgrep

on:
  push:
    branches: [ "appsec-lab9-ci" ]
  pull_request:
    branches: [ "appsec-lab9-ci" ]

permissions:
  contents: read

jobs:
  semgrep:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep:latest
    steps:
      # Checkout project source
      - uses: actions/checkout@v4
      - run: semgrep scan --config p/owasp-top-ten --sarif --output semgrep.sarif

      - uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep.sarif
          
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
        if: always()
